# Generated by Django 4.2.21 on 2025-06-13 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='messagelike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лайк сообщения', 'verbose_name_plural': 'Лайки сообщений'},
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='messagelike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата лайка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(help_text='Пользователи, участвующие в чате', related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(help_text='Чат, к которому относится сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Сообщение не может быть пустым')], verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='messagelike',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='messenger.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='messagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-updated_at'], name='messenger_c_updated_bf18fb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='messenger_m_chat_id_3bd072_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelike',
            index=models.Index(fields=['message', 'user'], name='messenger_m_message_847fa0_idx'),
        ),
    ]
