# Generated by Django 4.2.21 on 2025-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_chat_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название чата'),
        ),
    ]
