# Generated by Django 4.2.21 on 2025-06-13 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0005_alter_chat_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MessageLike',
        ),
    ]
