# Generated by Django 4.2.21 on 2025-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_remove_message_is_read_chat_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название чата'),
        ),
    ]
