# Generated by Django 4.2.21 on 2025-06-26 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0009_chat_deleted_for_message_deleted_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.AlterField(
            model_name='chat',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_chats', to=settings.AUTH_USER_MODEL, verbose_name='Скрыто для'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL, verbose_name='Скрыто для'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.CreateModel(
            name='MessageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='messenger.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк сообщения',
                'verbose_name_plural': 'Лайки сообщений',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
